site_name: Which algorithms
site_url: https://hanggrian.github.io/which-algorithms/
site_author: Hendra Anggrian
site_description: Personal note of programming algorithms and data structures

repo_name: hanggrian/which-algorithms
repo_url: https://github.com/hanggrian/which-algorithms

copyright: <a href="https://hanggrian.github.io">About me</a>

theme:
  name: material
  favicon: images/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light green
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: material/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.share
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - toc.follow
    - toc.integrate

nav:
  - Algorithms:
    - Index: index.md
    - Two pointers: two-pointers.md
  - Data structures:
    - Index: data-structures/index.md
    - Lists: data-structures/lists.md
    - Queues: data-structures/queues.md
    - Sets: data-structures/sets.md
    - Maps: data-structures/maps.md
  - Sorting:
    - Index: sorting/index.md
  - Searching:
    - Index: searching/index.md

plugins:
  - search

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

hooks:
  - hooks/archive.py

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn

# extra:
#   analytics:
#     provider: google
#     property: !ENV GOOGLE_ANALYTICS_KEY

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
